### ISSUE TITLE
Make deleting (untracked) files more foolproof

### ISSUE THREAD

**Issue by Ferada** [s3rvac/git-edit-index#1]
The first thing I did with this command was to open it, edit something, then delete the whole contents of the file and save, which lead to the deletion of some (unimportant) files. Why? Because I'm used to "empty buffer = do nothing" from the `git commit` command and some others (notably `git rebase` doesn't do that).

I wanted to suggest to make deleting files, especially untracked ones, harder, perhaps by having another prefix, e.g. `!` or something, to mean deletion, while deleting a whole line would be of no consequence.

Or maybe require an additional confirmation if the buffer is empty and it would do something irrevocable (config flag?).

**Comment by s3rvac** [comment]
Thank you for bringing this up. The reason why the command behaves the way it does is that by making the empty buffer do nothing, it would be impossible to e.g. clean the whole working directory simply by removing all lines in the buffer. I use this a lot. It is really fast, especially when using e.g. Vim, which allows one to clear a buffer with a single command.

Nevertheless, I agree with you that this behavior may be counterintuitive, especially when considering standard git commands. I would like to address that.

> I wanted to suggest to make deleting files, especially untracked ones, harder, perhaps by having another prefix, e.g. `!` or something, to mean deletion, while deleting a whole line would be of no consequence.

I would rather not introduce another prefix because (1) that would unnecessarily break backward compatibility and (2) may be counterintuitive when used e.g. to drop uncommited modifications from a file (this is currently also done by simply removing the corresponding line).

> Or maybe require an additional confirmation if the buffer is empty and it would do something irrevocable (config flag?).

I like this idea. Also, by adding a config option for this, users may decide whether they want to always request confirmation or they would like to keep the current behavior. I think I will implement this.

**Comment by s3rvac** [comment]
I have implemented this in commit 4b322ee4. When the editor buffer is empty (i.e. all lines were deleted), the command now asks the user whether he or she wants to reflect the changes. This makes the deletion of files or changes more foolproof.

The default behavior can be changed by setting the `git-edit-index.onEmptyBuffer` config option. It represents what should be done when the editor buffer is empty (i.e. all lines were deleted). Possible values:
- `ask`: Ask the user by showing him or her a `y/N` prompt. This is the default behavior of the command since version `0.5`.
- `act`: Reflect the changes, without asking. This was the default behavior of the command until version `0.5`.
- `nothing`: Do not reflect any changes, without asking. This corresponds to the default behavior of many other Git commands.
